export const MOVIE_DATA_RECENT = 'MOVIE_DATA_RECENT';
export const MOVIE_DATA_ALL = 'MOVIE_DATA_ALL';
export const MOVIE_DATA_PAGED = 'MOVIE_DATA_PAGED';
export const MOVIE_DETAILS = 'MOVIE_DETAILS';
export const SEARCH_MOVIE = 'SEARCH_MOVIE';
